-- ============================================================================
-- DỰ ÁN 1: XÂY DỰNG MÔ HÌNH PHÂN LOẠI VÀ DỰ BÁO RỦI RO KHÁCH HÀNG VAY VỐN
-- Script 01: Tạo bảng dữ liệu thô (Raw Tables Schema)
-- Tác giả: Phạm Đức Thắng (thang)
-- Ngày tạo: 2026-07-03
-- ============================================================================

-- Dọn dẹp các bảng cũ nếu đã tồn tại để tránh xung đột
DROP TABLE IF EXISTS application_train CASCADE;
DROP TABLE IF EXISTS application_test CASCADE;
DROP TABLE IF EXISTS bureau CASCADE;
DROP TABLE IF EXISTS bureau_balance CASCADE;
DROP TABLE IF EXISTS previous_application CASCADE;
DROP TABLE IF EXISTS pos_cash_balance CASCADE;
DROP TABLE IF EXISTS installments_payments CASCADE;
DROP TABLE IF EXISTS credit_card_balance CASCADE;

-- 1. BẢNG application_train: Đơn xin vay chính dùng để huấn luyện mô hình
CREATE TABLE application_train (
    sk_id_curr INT PRIMARY KEY,
    target INT,
    name_contract_type VARCHAR(255),
    code_gender VARCHAR(255),
    flag_own_car VARCHAR(255),
    flag_own_realty VARCHAR(255),
    cnt_children INT,
    amt_income_total DOUBLE PRECISION,
    amt_credit DOUBLE PRECISION,
    amt_annuity DOUBLE PRECISION,
    amt_goods_price DOUBLE PRECISION,
    name_type_suite VARCHAR(255),
    name_income_type VARCHAR(255),
    name_education_type VARCHAR(255),
    name_family_status VARCHAR(255),
    name_housing_type VARCHAR(255),
    region_population_relative DOUBLE PRECISION,
    days_birth INT,
    days_employed INT,
    days_registration DOUBLE PRECISION,
    days_id_publish INT,
    own_car_age DOUBLE PRECISION,
    flag_mobil SMALLINT,
    flag_emp_phone SMALLINT,
    flag_work_phone SMALLINT,
    flag_cont_mobile SMALLINT,
    flag_phone SMALLINT,
    flag_email SMALLINT,
    occupation_type VARCHAR(255),
    cnt_fam_members DOUBLE PRECISION,
    region_rating_client INT,
    region_rating_client_w_city INT,
    weekday_appr_process_start VARCHAR(255),
    hour_appr_process_start INT,
    reg_region_not_live_region INT,
    reg_region_not_work_region INT,
    live_region_not_work_region INT,
    reg_city_not_live_city INT,
    reg_city_not_work_city INT,
    live_city_not_work_city INT,
    organization_type VARCHAR(255),
    ext_source_1 DOUBLE PRECISION,
    ext_source_2 DOUBLE PRECISION,
    ext_source_3 DOUBLE PRECISION,
    apartments_avg DOUBLE PRECISION,
    basementarea_avg DOUBLE PRECISION,
    years_beginexpluatation_avg DOUBLE PRECISION,
    years_build_avg DOUBLE PRECISION,
    commonarea_avg DOUBLE PRECISION,
    elevators_avg DOUBLE PRECISION,
    entrances_avg DOUBLE PRECISION,
    floorsmax_avg DOUBLE PRECISION,
    floorsmin_avg DOUBLE PRECISION,
    landarea_avg DOUBLE PRECISION,
    livingapartments_avg DOUBLE PRECISION,
    livingarea_avg DOUBLE PRECISION,
    nonlivingapartments_avg DOUBLE PRECISION,
    nonlivingarea_avg DOUBLE PRECISION,
    apartments_mode DOUBLE PRECISION,
    basementarea_mode DOUBLE PRECISION,
    years_beginexpluatation_mode DOUBLE PRECISION,
    years_build_mode DOUBLE PRECISION,
    commonarea_mode DOUBLE PRECISION,
    elevators_mode DOUBLE PRECISION,
    entrances_mode DOUBLE PRECISION,
    floorsmax_mode DOUBLE PRECISION,
    floorsmin_mode DOUBLE PRECISION,
    landarea_mode DOUBLE PRECISION,
    livingapartments_mode DOUBLE PRECISION,
    livingarea_mode DOUBLE PRECISION,
    nonlivingapartments_mode DOUBLE PRECISION,
    nonlivingarea_mode DOUBLE PRECISION,
    apartments_medi DOUBLE PRECISION,
    basementarea_medi DOUBLE PRECISION,
    years_beginexpluatation_medi DOUBLE PRECISION,
    years_build_medi DOUBLE PRECISION,
    commonarea_medi DOUBLE PRECISION,
    elevators_medi DOUBLE PRECISION,
    entrances_medi DOUBLE PRECISION,
    floorsmax_medi DOUBLE PRECISION,
    floorsmin_medi DOUBLE PRECISION,
    landarea_medi DOUBLE PRECISION,
    livingapartments_medi DOUBLE PRECISION,
    livingarea_medi DOUBLE PRECISION,
    nonlivingapartments_medi DOUBLE PRECISION,
    nonlivingarea_medi DOUBLE PRECISION,
    fondkapremont_mode VARCHAR(255),
    housetype_mode VARCHAR(255),
    totalarea_mode DOUBLE PRECISION,
    wallsmaterial_mode VARCHAR(255),
    emergencystate_mode VARCHAR(255),
    obs_30_cnt_social_circle DOUBLE PRECISION,
    def_30_cnt_social_circle DOUBLE PRECISION,
    obs_60_cnt_social_circle DOUBLE PRECISION,
    def_60_cnt_social_circle DOUBLE PRECISION,
    days_last_phone_change DOUBLE PRECISION,
    flag_document_2 SMALLINT,
    flag_document_3 SMALLINT,
    flag_document_4 SMALLINT,
    flag_document_5 SMALLINT,
    flag_document_6 SMALLINT,
    flag_document_7 SMALLINT,
    flag_document_8 SMALLINT,
    flag_document_9 SMALLINT,
    flag_document_10 SMALLINT,
    flag_document_11 SMALLINT,
    flag_document_12 SMALLINT,
    flag_document_13 SMALLINT,
    flag_document_14 SMALLINT,
    flag_document_15 SMALLINT,
    flag_document_16 SMALLINT,
    flag_document_17 SMALLINT,
    flag_document_18 SMALLINT,
    flag_document_19 SMALLINT,
    flag_document_20 SMALLINT,
    flag_document_21 SMALLINT,
    amt_req_credit_bureau_hour DOUBLE PRECISION,
    amt_req_credit_bureau_day DOUBLE PRECISION,
    amt_req_credit_bureau_week DOUBLE PRECISION,
    amt_req_credit_bureau_mon DOUBLE PRECISION,
    amt_req_credit_bureau_qrt DOUBLE PRECISION,
    amt_req_credit_bureau_year DOUBLE PRECISION
);

-- 2. BẢNG application_test: Đơn xin vay chính dùng để kiểm thử mô hình
CREATE TABLE application_test (
    sk_id_curr INT PRIMARY KEY,
    name_contract_type VARCHAR(255),
    code_gender VARCHAR(255),
    flag_own_car VARCHAR(255),
    flag_own_realty VARCHAR(255),
    cnt_children INT,
    amt_income_total DOUBLE PRECISION,
    amt_credit DOUBLE PRECISION,
    amt_annuity DOUBLE PRECISION,
    amt_goods_price DOUBLE PRECISION,
    name_type_suite VARCHAR(255),
    name_income_type VARCHAR(255),
    name_education_type VARCHAR(255),
    name_family_status VARCHAR(255),
    name_housing_type VARCHAR(255),
    region_population_relative DOUBLE PRECISION,
    days_birth INT,
    days_employed INT,
    days_registration DOUBLE PRECISION,
    days_id_publish INT,
    own_car_age DOUBLE PRECISION,
    flag_mobil SMALLINT,
    flag_emp_phone SMALLINT,
    flag_work_phone SMALLINT,
    flag_cont_mobile SMALLINT,
    flag_phone SMALLINT,
    flag_email SMALLINT,
    occupation_type VARCHAR(255),
    cnt_fam_members DOUBLE PRECISION,
    region_rating_client INT,
    region_rating_client_w_city INT,
    weekday_appr_process_start VARCHAR(255),
    hour_appr_process_start INT,
    reg_region_not_live_region INT,
    reg_region_not_work_region INT,
    live_region_not_work_region INT,
    reg_city_not_live_city INT,
    reg_city_not_work_city INT,
    live_city_not_work_city INT,
    organization_type VARCHAR(255),
    ext_source_1 DOUBLE PRECISION,
    ext_source_2 DOUBLE PRECISION,
    ext_source_3 DOUBLE PRECISION,
    apartments_avg DOUBLE PRECISION,
    basementarea_avg DOUBLE PRECISION,
    years_beginexpluatation_avg DOUBLE PRECISION,
    years_build_avg DOUBLE PRECISION,
    commonarea_avg DOUBLE PRECISION,
    elevators_avg DOUBLE PRECISION,
    entrances_avg DOUBLE PRECISION,
    floorsmax_avg DOUBLE PRECISION,
    floorsmin_avg DOUBLE PRECISION,
    landarea_avg DOUBLE PRECISION,
    livingapartments_avg DOUBLE PRECISION,
    livingarea_avg DOUBLE PRECISION,
    nonlivingapartments_avg DOUBLE PRECISION,
    nonlivingarea_avg DOUBLE PRECISION,
    apartments_mode DOUBLE PRECISION,
    basementarea_mode DOUBLE PRECISION,
    years_beginexpluatation_mode DOUBLE PRECISION,
    years_build_mode DOUBLE PRECISION,
    commonarea_mode DOUBLE PRECISION,
    elevators_mode DOUBLE PRECISION,
    entrances_mode DOUBLE PRECISION,
    floorsmax_mode DOUBLE PRECISION,
    floorsmin_mode DOUBLE PRECISION,
    landarea_mode DOUBLE PRECISION,
    livingapartments_mode DOUBLE PRECISION,
    livingarea_mode DOUBLE PRECISION,
    nonlivingapartments_mode DOUBLE PRECISION,
    nonlivingarea_mode DOUBLE PRECISION,
    apartments_medi DOUBLE PRECISION,
    basementarea_medi DOUBLE PRECISION,
    years_beginexpluatation_medi DOUBLE PRECISION,
    years_build_medi DOUBLE PRECISION,
    commonarea_medi DOUBLE PRECISION,
    elevators_medi DOUBLE PRECISION,
    entrances_medi DOUBLE PRECISION,
    floorsmax_medi DOUBLE PRECISION,
    floorsmin_medi DOUBLE PRECISION,
    landarea_medi DOUBLE PRECISION,
    livingapartments_medi DOUBLE PRECISION,
    livingarea_medi DOUBLE PRECISION,
    nonlivingapartments_medi DOUBLE PRECISION,
    nonlivingarea_medi DOUBLE PRECISION,
    fondkapremont_mode VARCHAR(255),
    housetype_mode VARCHAR(255),
    totalarea_mode DOUBLE PRECISION,
    wallsmaterial_mode VARCHAR(255),
    emergencystate_mode VARCHAR(255),
    obs_30_cnt_social_circle DOUBLE PRECISION,
    def_30_cnt_social_circle DOUBLE PRECISION,
    obs_60_cnt_social_circle DOUBLE PRECISION,
    def_60_cnt_social_circle DOUBLE PRECISION,
    days_last_phone_change DOUBLE PRECISION,
    flag_document_2 SMALLINT,
    flag_document_3 SMALLINT,
    flag_document_4 SMALLINT,
    flag_document_5 SMALLINT,
    flag_document_6 SMALLINT,
    flag_document_7 SMALLINT,
    flag_document_8 SMALLINT,
    flag_document_9 SMALLINT,
    flag_document_10 SMALLINT,
    flag_document_11 SMALLINT,
    flag_document_12 SMALLINT,
    flag_document_13 SMALLINT,
    flag_document_14 SMALLINT,
    flag_document_15 SMALLINT,
    flag_document_16 SMALLINT,
    flag_document_17 SMALLINT,
    flag_document_18 SMALLINT,
    flag_document_19 SMALLINT,
    flag_document_20 SMALLINT,
    flag_document_21 SMALLINT,
    amt_req_credit_bureau_hour DOUBLE PRECISION,
    amt_req_credit_bureau_day DOUBLE PRECISION,
    amt_req_credit_bureau_week DOUBLE PRECISION,
    amt_req_credit_bureau_mon DOUBLE PRECISION,
    amt_req_credit_bureau_qrt DOUBLE PRECISION,
    amt_req_credit_bureau_year DOUBLE PRECISION
);

-- 3. BẢNG bureau: Lịch sử các khoản vay của khách hàng tại tổ chức tài chính khác (thông tin CIC)
CREATE TABLE bureau (
    sk_id_curr INT,
    sk_id_bureau INT PRIMARY KEY,
    credit_active VARCHAR(255),
    credit_currency VARCHAR(255),
    days_credit INT,
    credit_day_overdue INT,
    days_credit_enddate DOUBLE PRECISION,
    days_enddate_fact DOUBLE PRECISION,
    amt_credit_max_overdue DOUBLE PRECISION,
    cnt_credit_prolong INT,
    amt_credit_sum DOUBLE PRECISION,
    amt_credit_sum_debt DOUBLE PRECISION,
    amt_credit_sum_limit DOUBLE PRECISION,
    amt_credit_sum_overdue DOUBLE PRECISION,
    credit_type VARCHAR(255),
    days_credit_update INT,
    amt_annuity DOUBLE PRECISION
);

-- 4. BẢNG bureau_balance: Số dư lịch sử hàng tháng của các khoản vay trong bảng bureau
CREATE TABLE bureau_balance (
    sk_id_bureau INT,
    months_balance INT,
    status VARCHAR(255),
    PRIMARY KEY (sk_id_bureau, months_balance)
);

-- 5. BẢNG previous_application: Tất cả các đơn xin vay trước đó tại chính Home Credit của khách hàng
CREATE TABLE previous_application (
    sk_id_prev INT PRIMARY KEY,
    sk_id_curr INT,
    name_contract_type VARCHAR(255),
    amt_annuity DOUBLE PRECISION,
    amt_application DOUBLE PRECISION,
    amt_credit DOUBLE PRECISION,
    amt_down_payment DOUBLE PRECISION,
    amt_goods_price DOUBLE PRECISION,
    weekday_appr_process_start VARCHAR(255),
    hour_appr_process_start INT,
    flag_last_appl_per_contract VARCHAR(255),
    nflag_last_appl_in_day INT,
    rate_down_payment DOUBLE PRECISION,
    rate_interest_primary DOUBLE PRECISION,
    rate_interest_privileged DOUBLE PRECISION,
    name_cash_loan_purpose VARCHAR(255),
    name_contract_status VARCHAR(255),
    days_decision INT,
    name_payment_type VARCHAR(255),
    code_reject_reason VARCHAR(255),
    name_type_suite VARCHAR(255),
    name_client_type VARCHAR(255),
    name_goods_category VARCHAR(255),
    name_portfolio VARCHAR(255),
    name_product_type VARCHAR(255),
    channel_type VARCHAR(255),
    sellerplace_area INT,
    name_seller_industry VARCHAR(255),
    cnt_payment DOUBLE PRECISION,
    name_yield_group VARCHAR(255),
    product_combination VARCHAR(255),
    days_first_drawing DOUBLE PRECISION,
    days_first_due DOUBLE PRECISION,
    days_last_due_1st_version DOUBLE PRECISION,
    days_last_due DOUBLE PRECISION,
    days_termination DOUBLE PRECISION,
    nflag_insured_on_approval DOUBLE PRECISION
);

-- 6. BẢNG pos_cash_balance: Số dư lịch sử hàng tháng của khoản vay POS hoặc Cash trước đó
CREATE TABLE pos_cash_balance (
    sk_id_prev INT,
    sk_id_curr INT,
    months_balance INT,
    cnt_instalment DOUBLE PRECISION,
    cnt_instalment_future DOUBLE PRECISION,
    name_contract_status VARCHAR(255),
    sk_dpd INT,
    sk_dpd_def INT
);

-- 7. BẢNG installments_payments: Lịch sử thanh toán thực tế của các khoản vay trước đó tại Home Credit
CREATE TABLE installments_payments (
    sk_id_prev INT,
    sk_id_curr INT,
    num_instalment_version DOUBLE PRECISION,
    num_instalment_number INT,
    days_instalment DOUBLE PRECISION,
    days_entry_payment DOUBLE PRECISION,
    amt_instalment DOUBLE PRECISION,
    amt_payment DOUBLE PRECISION
);

-- 8. BẢNG credit_card_balance: Số dư lịch sử hàng tháng của các khoản vay thẻ tín dụng trước đó
CREATE TABLE credit_card_balance (
    sk_id_prev INT,
    sk_id_curr INT,
    months_balance INT,
    amt_balance DOUBLE PRECISION,
    amt_credit_limit_actual INT,
    amt_drawings_atm_current DOUBLE PRECISION,
    amt_drawings_current DOUBLE PRECISION,
    amt_drawings_other_current DOUBLE PRECISION,
    amt_drawings_pos_current DOUBLE PRECISION,
    amt_inst_min_regularity DOUBLE PRECISION,
    amt_payment_current DOUBLE PRECISION,
    amt_payment_total_current DOUBLE PRECISION,
    amt_receivable_principal DOUBLE PRECISION,
    amt_recivable DOUBLE PRECISION,
    amt_total_receivable DOUBLE PRECISION,
    cnt_drawings_atm_current DOUBLE PRECISION,
    cnt_drawings_current INT,
    cnt_drawings_other_current DOUBLE PRECISION,
    cnt_drawings_pos_current DOUBLE PRECISION,
    cnt_instalment_mature_cum DOUBLE PRECISION,
    name_contract_status VARCHAR(255),
    sk_dpd INT,
    sk_dpd_def INT
);
