-- 02_create_raw_tables.sql
-- Mục đích: tạo 8 bảng raw từ 8 file CSV chính của Home Credit.
-- Kiểu dữ liệu được khai báo gần với dữ liệu gốc để vừa dễ import vừa dễ giải thích.
-- Chạy file này sau khi đã kết nối vào database credit_risk_db.

-- Bảng raw từ file application_train.csv
DROP TABLE IF EXISTS application_train CASCADE;
CREATE TABLE application_train (
    sk_id_curr BIGINT,
    target SMALLINT,
    name_contract_type TEXT,
    code_gender TEXT,
    flag_own_car SMALLINT,
    flag_own_realty SMALLINT,
    cnt_children NUMERIC,
    amt_income_total NUMERIC,
    amt_credit NUMERIC,
    amt_annuity NUMERIC,
    amt_goods_price NUMERIC,
    name_type_suite TEXT,
    name_income_type TEXT,
    name_education_type TEXT,
    name_family_status TEXT,
    name_housing_type TEXT,
    region_population_relative NUMERIC,
    days_birth NUMERIC,
    days_employed NUMERIC,
    days_registration NUMERIC,
    days_id_publish NUMERIC,
    own_car_age NUMERIC,
    flag_mobil SMALLINT,
    flag_emp_phone SMALLINT,
    flag_work_phone SMALLINT,
    flag_cont_mobile SMALLINT,
    flag_phone SMALLINT,
    flag_email SMALLINT,
    occupation_type TEXT,
    cnt_fam_members NUMERIC,
    region_rating_client NUMERIC,
    region_rating_client_w_city NUMERIC,
    weekday_appr_process_start TEXT,
    hour_appr_process_start NUMERIC,
    reg_region_not_live_region SMALLINT,
    reg_region_not_work_region SMALLINT,
    live_region_not_work_region SMALLINT,
    reg_city_not_live_city SMALLINT,
    reg_city_not_work_city SMALLINT,
    live_city_not_work_city SMALLINT,
    organization_type TEXT,
    ext_source_1 NUMERIC,
    ext_source_2 NUMERIC,
    ext_source_3 NUMERIC,
    apartments_avg NUMERIC,
    basementarea_avg NUMERIC,
    years_beginexpluatation_avg NUMERIC,
    years_build_avg NUMERIC,
    commonarea_avg NUMERIC,
    elevators_avg NUMERIC,
    entrances_avg NUMERIC,
    floorsmax_avg NUMERIC,
    floorsmin_avg NUMERIC,
    landarea_avg NUMERIC,
    livingapartments_avg NUMERIC,
    livingarea_avg NUMERIC,
    nonlivingapartments_avg NUMERIC,
    nonlivingarea_avg NUMERIC,
    apartments_mode NUMERIC,
    basementarea_mode NUMERIC,
    years_beginexpluatation_mode NUMERIC,
    years_build_mode NUMERIC,
    commonarea_mode NUMERIC,
    elevators_mode NUMERIC,
    entrances_mode NUMERIC,
    floorsmax_mode NUMERIC,
    floorsmin_mode NUMERIC,
    landarea_mode NUMERIC,
    livingapartments_mode NUMERIC,
    livingarea_mode NUMERIC,
    nonlivingapartments_mode NUMERIC,
    nonlivingarea_mode NUMERIC,
    apartments_medi NUMERIC,
    basementarea_medi NUMERIC,
    years_beginexpluatation_medi NUMERIC,
    years_build_medi NUMERIC,
    commonarea_medi NUMERIC,
    elevators_medi NUMERIC,
    entrances_medi NUMERIC,
    floorsmax_medi NUMERIC,
    floorsmin_medi NUMERIC,
    landarea_medi NUMERIC,
    livingapartments_medi NUMERIC,
    livingarea_medi NUMERIC,
    nonlivingapartments_medi NUMERIC,
    nonlivingarea_medi NUMERIC,
    fondkapremont_mode TEXT,
    housetype_mode TEXT,
    totalarea_mode NUMERIC,
    wallsmaterial_mode TEXT,
    emergencystate_mode TEXT,
    obs_30_cnt_social_circle NUMERIC,
    def_30_cnt_social_circle NUMERIC,
    obs_60_cnt_social_circle NUMERIC,
    def_60_cnt_social_circle NUMERIC,
    days_last_phone_change NUMERIC,
    flag_document_2 SMALLINT,
    flag_document_3 SMALLINT,
    flag_document_4 SMALLINT,
    flag_document_5 SMALLINT,
    flag_document_6 SMALLINT,
    flag_document_7 SMALLINT,
    flag_document_8 SMALLINT,
    flag_document_9 SMALLINT,
    flag_document_10 SMALLINT,
    flag_document_11 SMALLINT,
    flag_document_12 SMALLINT,
    flag_document_13 SMALLINT,
    flag_document_14 SMALLINT,
    flag_document_15 SMALLINT,
    flag_document_16 SMALLINT,
    flag_document_17 SMALLINT,
    flag_document_18 SMALLINT,
    flag_document_19 SMALLINT,
    flag_document_20 SMALLINT,
    flag_document_21 SMALLINT,
    amt_req_credit_bureau_hour NUMERIC,
    amt_req_credit_bureau_day NUMERIC,
    amt_req_credit_bureau_week NUMERIC,
    amt_req_credit_bureau_mon NUMERIC,
    amt_req_credit_bureau_qrt NUMERIC,
    amt_req_credit_bureau_year NUMERIC
);

-- Bảng raw từ file application_test.csv
DROP TABLE IF EXISTS application_test CASCADE;
CREATE TABLE application_test (
    sk_id_curr BIGINT,
    name_contract_type TEXT,
    code_gender TEXT,
    flag_own_car SMALLINT,
    flag_own_realty SMALLINT,
    cnt_children NUMERIC,
    amt_income_total NUMERIC,
    amt_credit NUMERIC,
    amt_annuity NUMERIC,
    amt_goods_price NUMERIC,
    name_type_suite TEXT,
    name_income_type TEXT,
    name_education_type TEXT,
    name_family_status TEXT,
    name_housing_type TEXT,
    region_population_relative NUMERIC,
    days_birth NUMERIC,
    days_employed NUMERIC,
    days_registration NUMERIC,
    days_id_publish NUMERIC,
    own_car_age NUMERIC,
    flag_mobil SMALLINT,
    flag_emp_phone SMALLINT,
    flag_work_phone SMALLINT,
    flag_cont_mobile SMALLINT,
    flag_phone SMALLINT,
    flag_email SMALLINT,
    occupation_type TEXT,
    cnt_fam_members NUMERIC,
    region_rating_client NUMERIC,
    region_rating_client_w_city NUMERIC,
    weekday_appr_process_start TEXT,
    hour_appr_process_start NUMERIC,
    reg_region_not_live_region SMALLINT,
    reg_region_not_work_region SMALLINT,
    live_region_not_work_region SMALLINT,
    reg_city_not_live_city SMALLINT,
    reg_city_not_work_city SMALLINT,
    live_city_not_work_city SMALLINT,
    organization_type TEXT,
    ext_source_1 NUMERIC,
    ext_source_2 NUMERIC,
    ext_source_3 NUMERIC,
    apartments_avg NUMERIC,
    basementarea_avg NUMERIC,
    years_beginexpluatation_avg NUMERIC,
    years_build_avg NUMERIC,
    commonarea_avg NUMERIC,
    elevators_avg NUMERIC,
    entrances_avg NUMERIC,
    floorsmax_avg NUMERIC,
    floorsmin_avg NUMERIC,
    landarea_avg NUMERIC,
    livingapartments_avg NUMERIC,
    livingarea_avg NUMERIC,
    nonlivingapartments_avg NUMERIC,
    nonlivingarea_avg NUMERIC,
    apartments_mode NUMERIC,
    basementarea_mode NUMERIC,
    years_beginexpluatation_mode NUMERIC,
    years_build_mode NUMERIC,
    commonarea_mode NUMERIC,
    elevators_mode NUMERIC,
    entrances_mode NUMERIC,
    floorsmax_mode NUMERIC,
    floorsmin_mode NUMERIC,
    landarea_mode NUMERIC,
    livingapartments_mode NUMERIC,
    livingarea_mode NUMERIC,
    nonlivingapartments_mode NUMERIC,
    nonlivingarea_mode NUMERIC,
    apartments_medi NUMERIC,
    basementarea_medi NUMERIC,
    years_beginexpluatation_medi NUMERIC,
    years_build_medi NUMERIC,
    commonarea_medi NUMERIC,
    elevators_medi NUMERIC,
    entrances_medi NUMERIC,
    floorsmax_medi NUMERIC,
    floorsmin_medi NUMERIC,
    landarea_medi NUMERIC,
    livingapartments_medi NUMERIC,
    livingarea_medi NUMERIC,
    nonlivingapartments_medi NUMERIC,
    nonlivingarea_medi NUMERIC,
    fondkapremont_mode TEXT,
    housetype_mode TEXT,
    totalarea_mode NUMERIC,
    wallsmaterial_mode TEXT,
    emergencystate_mode TEXT,
    obs_30_cnt_social_circle NUMERIC,
    def_30_cnt_social_circle NUMERIC,
    obs_60_cnt_social_circle NUMERIC,
    def_60_cnt_social_circle NUMERIC,
    days_last_phone_change NUMERIC,
    flag_document_2 SMALLINT,
    flag_document_3 SMALLINT,
    flag_document_4 SMALLINT,
    flag_document_5 SMALLINT,
    flag_document_6 SMALLINT,
    flag_document_7 SMALLINT,
    flag_document_8 SMALLINT,
    flag_document_9 SMALLINT,
    flag_document_10 SMALLINT,
    flag_document_11 SMALLINT,
    flag_document_12 SMALLINT,
    flag_document_13 SMALLINT,
    flag_document_14 SMALLINT,
    flag_document_15 SMALLINT,
    flag_document_16 SMALLINT,
    flag_document_17 SMALLINT,
    flag_document_18 SMALLINT,
    flag_document_19 SMALLINT,
    flag_document_20 SMALLINT,
    flag_document_21 SMALLINT,
    amt_req_credit_bureau_hour NUMERIC,
    amt_req_credit_bureau_day NUMERIC,
    amt_req_credit_bureau_week NUMERIC,
    amt_req_credit_bureau_mon NUMERIC,
    amt_req_credit_bureau_qrt NUMERIC,
    amt_req_credit_bureau_year NUMERIC
);

-- Bảng raw từ file bureau.csv
DROP TABLE IF EXISTS bureau CASCADE;
CREATE TABLE bureau (
    sk_id_curr BIGINT,
    sk_id_bureau BIGINT,
    credit_active TEXT,
    credit_currency TEXT,
    days_credit NUMERIC,
    credit_day_overdue TEXT,
    days_credit_enddate NUMERIC,
    days_enddate_fact NUMERIC,
    amt_credit_max_overdue NUMERIC,
    cnt_credit_prolong NUMERIC,
    amt_credit_sum NUMERIC,
    amt_credit_sum_debt NUMERIC,
    amt_credit_sum_limit NUMERIC,
    amt_credit_sum_overdue NUMERIC,
    credit_type TEXT,
    days_credit_update NUMERIC,
    amt_annuity NUMERIC
);

-- Bảng raw từ file bureau_balance.csv
DROP TABLE IF EXISTS bureau_balance CASCADE;
CREATE TABLE bureau_balance (
    sk_id_bureau BIGINT,
    months_balance NUMERIC,
    status TEXT
);

-- Bảng raw từ file previous_application.csv
DROP TABLE IF EXISTS previous_application CASCADE;
CREATE TABLE previous_application (
    sk_id_prev BIGINT,
    sk_id_curr BIGINT,
    name_contract_type TEXT,
    amt_annuity NUMERIC,
    amt_application NUMERIC,
    amt_credit NUMERIC,
    amt_down_payment NUMERIC,
    amt_goods_price NUMERIC,
    weekday_appr_process_start TEXT,
    hour_appr_process_start NUMERIC,
    flag_last_appl_per_contract SMALLINT,
    nflag_last_appl_in_day SMALLINT,
    rate_down_payment NUMERIC,
    rate_interest_primary NUMERIC,
    rate_interest_privileged NUMERIC,
    name_cash_loan_purpose TEXT,
    name_contract_status TEXT,
    days_decision NUMERIC,
    name_payment_type TEXT,
    code_reject_reason TEXT,
    name_type_suite TEXT,
    name_client_type TEXT,
    name_goods_category TEXT,
    name_portfolio TEXT,
    name_product_type TEXT,
    channel_type TEXT,
    sellerplace_area NUMERIC,
    name_seller_industry TEXT,
    cnt_payment NUMERIC,
    name_yield_group TEXT,
    product_combination TEXT,
    days_first_drawing NUMERIC,
    days_first_due NUMERIC,
    days_last_due_1st_version NUMERIC,
    days_last_due NUMERIC,
    days_termination NUMERIC,
    nflag_insured_on_approval SMALLINT
);

-- Bảng raw từ file installments_payments.csv
DROP TABLE IF EXISTS installments_payments CASCADE;
CREATE TABLE installments_payments (
    sk_id_prev BIGINT,
    sk_id_curr BIGINT,
    num_instalment_version NUMERIC,
    num_instalment_number NUMERIC,
    days_instalment NUMERIC,
    days_entry_payment NUMERIC,
    amt_instalment NUMERIC,
    amt_payment NUMERIC
);

-- Bảng raw từ file POS_CASH_balance.csv
DROP TABLE IF EXISTS pos_cash_balance CASCADE;
CREATE TABLE pos_cash_balance (
    sk_id_prev BIGINT,
    sk_id_curr BIGINT,
    months_balance NUMERIC,
    cnt_instalment NUMERIC,
    cnt_instalment_future NUMERIC,
    name_contract_status TEXT,
    sk_dpd NUMERIC,
    sk_dpd_def NUMERIC
);

-- Bảng raw từ file credit_card_balance.csv
DROP TABLE IF EXISTS credit_card_balance CASCADE;
CREATE TABLE credit_card_balance (
    sk_id_prev BIGINT,
    sk_id_curr BIGINT,
    months_balance NUMERIC,
    amt_balance NUMERIC,
    amt_credit_limit_actual NUMERIC,
    amt_drawings_atm_current NUMERIC,
    amt_drawings_current NUMERIC,
    amt_drawings_other_current NUMERIC,
    amt_drawings_pos_current NUMERIC,
    amt_inst_min_regularity NUMERIC,
    amt_payment_current NUMERIC,
    amt_payment_total_current NUMERIC,
    amt_receivable_principal NUMERIC,
    amt_recivable NUMERIC,
    amt_total_receivable NUMERIC,
    cnt_drawings_atm_current NUMERIC,
    cnt_drawings_current NUMERIC,
    cnt_drawings_other_current NUMERIC,
    cnt_drawings_pos_current NUMERIC,
    cnt_instalment_mature_cum NUMERIC,
    name_contract_status TEXT,
    sk_dpd NUMERIC,
    sk_dpd_def NUMERIC
);
